# Generated by Django 6.0.4 on 2026-06-12 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmevent',
            name='alarm_type',
            field=models.CharField(choices=[('tailgating', '尾随通行'), ('forced_open', '暴力开门'), ('device_offline', '设备离线'), ('blacklist', '黑名单告警'), ('nighttime_denied', '夜间拒绝开门')], max_length=30),
        ),
        migrations.CreateModel(
            name='NighttimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='夜间时段开始时间，例如 22:00')),
                ('end_time', models.TimeField(help_text='夜间时段结束时间，例如 06:00')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nighttime_rule', to='access.accessdevice')),
            ],
            options={
                'ordering': ['device__device_code'],
            },
        ),
    ]
